apiVersion: batch/v1
kind: Job
metadata:
  name: day2-gitops-api-server-certificates
  namespace: test-gitops
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: apply-api-server-certificate
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - echo "Applying cert with user $API_USERNAME"
          env:
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-server-credentials
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-server-credentials
                  key: password
  backoffLimit: 2
